"""Update User Model

Revision ID: c295e62e7071
Revises: 436e9d00413b
Create Date: 2025-03-17 03:39:43.336292

"""

from typing import Sequence, Union

# import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c295e62e7071"
down_revision: Union[str, None] = "436e9d00413b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
